name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t baby-photoshoot-app:latest .

      - name: Save Docker image to a tar file
        run: docker save baby-photoshoot-app:latest -o baby-photoshoot-app.tar

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Copy Docker image to DigitalOcean
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          source: "baby-photoshoot-app.tar"
          target: "~/baby-photoshoot-app.tar"
          debug: true

      - name: SSH and load Docker image on DigitalOcean
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          script: |
            docker load -i ~/baby-photoshoot-app.tar
            docker run -d -p 80:3000 baby-photoshoot-app:latest
