name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t baby-photoshoot-app:latest .

      - name: Save Docker image to a tar file
        run: docker save baby-photoshoot-app:latest -o baby-photoshoot-app.tar

      - name: Setup SSH Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> $HOME/.ssh/known_hosts

      - name: Transfer Docker image using Rsync
        run: |
          rsync -avz -e "ssh -i $HOME/.ssh/id_rsa" baby-photoshoot-app.tar ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }}:/home/${{ secrets.DROPLET_USERNAME }}/

      - name: Deploy Application
        run: |
          ssh -i $HOME/.ssh/id_rsa ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} "\
          docker ps -q --filter 'publish=80' | xargs -r docker stop | xargs -r docker rm; \
          docker stop baby-photoshoot-app 2>/dev/null || true; \
          docker rm baby-photoshoot-app 2>/dev/null || true; \
          docker load -i /home/${{ secrets.DROPLET_USERNAME }}/baby-photoshoot-app.tar && \
          docker run -d -p 80:3000 --name baby-photoshoot-app baby-photoshoot-app:latest"
