name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t baby-photoshoot-app:latest .

      - name: Save Docker image to a tar file
        run: docker save baby-photoshoot-app:latest -o baby-photoshoot-app.tar

      - name: Setup SSH Agent and Add Key
        run: |
          mkdir -p $HOME/.ssh
          chmod 700 $HOME/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > $HOME/.ssh/harshi
          chmod 600 $HOME/.ssh/harshi
          eval "$(ssh-agent -s)"
          ssh-add $HOME/.ssh/harshi
        shell: bash # Use Bash shell to execute these commands

      - name: Copy Docker image to DigitalOcean
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.DROPLET_IP }} # IP address or hostname of your DigitalOcean server
          username: ${{ secrets.DROPLET_USERNAME }} # Username to use for the server
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "baby-photoshoot-app.tar" # Source file to copy
          target: "~/baby-photoshoot-app.tar" # Target location on the server
          debug: true # Enable debug output
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }} # Use the SSH agent socket

      - name: Load Docker image on DigitalOcean
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          script: |
            docker load -i ~/baby-photoshow-app.tar  # Load the Docker image from the tar file
            docker run -d -p 80:3000 baby-photoshoot-app:latest  # Run the Docker container
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }} # Use the SSH agent socket
